module.exports = {
  content: ["./*.html", "./assets/**/*.js"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2d3133",
        "on-primary-fixed-variant": "#134391",
        outline: "#747782",
        background: "#f7f9fc",
        primary: "#00347b",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#321200",
        "inverse-primary": "#afc6ff",
        "tertiary-fixed-dim": "#ffb68b",
        "surface-dim": "#d8dadd",
        "on-error": "#ffffff",
        "on-surface-variant": "#434651",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e0e3e6",
        "tertiary-container": "#803a00",
        "mint-success": "#E9F8EF",
        "tertiary-fixed": "#ffdbc8",
        "on-background": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eff1f4",
        "surface-bright": "#f7f9fc",
        "on-secondary-fixed-variant": "#344769",
        error: "#ba1a1a",
        "outline-variant": "#c3c6d3",
        "on-tertiary-container": "#ffad7a",
        "secondary-container": "#c1d5fe",
        "surface-container-low": "#f2f4f7",
        "lavender-ai": "#EEEAFE",
        "on-secondary-fixed": "#041b3b",
        "pink-alert": "#FDECEF",
        "status-high": "#E53935",
        "on-surface": "#191c1e",
        "surface-container-high": "#e6e8eb",
        "status-low": "#43A047",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001944",
        "status-medium": "#FB8C00",
        "border-subtle": "#E4EAF3",
        "primary-fixed": "#d9e2ff",
        surface: "#f7f9fc",
        "surface-container": "#eceef1",
        "surface-tint": "#335caa",
        "on-secondary-container": "#495c7f",
        "surface-container-highest": "#e0e3e6",
        "secondary-fixed": "#d7e3ff",
        "on-primary-container": "#a5bfff",
        "primary-container": "#1f4b99",
        "on-secondary": "#ffffff",
        tertiary: "#5d2800",
        "surface-accent": "#EEF4FF",
        "primary-fixed-dim": "#afc6ff",
        "on-tertiary-fixed-variant": "#753400",
        "secondary-fixed-dim": "#b3c7f0",
        secondary: "#4b5f82",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1rem",
        "card-gap": "1.5rem",
        "sidebar-width": "260px",
        "container-padding": "2rem",
        "section-margin": "2.5rem",
      },
      fontFamily: {
        "label-bold": ["IBM Plex Sans", "sans-serif"],
        "body-base": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "title-sm": ["IBM Plex Sans", "sans-serif"],
        "display-lg": ["IBM Plex Sans", "sans-serif"],
        "label-sm": ["IBM Plex Sans", "sans-serif"],
        "headline-md": ["IBM Plex Sans", "sans-serif"],
      },
      fontSize: {
        "label-bold": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
};
